### ISSUE TITLE
Always overwrite securityContexts Userid

### ISSUE THREAD

**Issue by stafwag-idirect** [kubewarden/user-group-psp-policy#3]
Hi,

Is there an option available to always overwrite the runAsUser/runAsGroup settings even when it is already defined in the manifest?

Kind regards,

--
staf

**Comment by jvanz** [comment]
Hi @stafwag-idirect ! Sorry for the long delay to give you a feedback! 

Unfortunately, the `policy-user-group` is intended to be a replacement for the PSP related to the user and group settings. Therefore, it does not have this feature. However, I liked your idea. I'll mark this issue as an enhancement request to be evaluated! 

If you would like to implement such a feature. Let us know!
