### ISSUE TITLE
why does userid have to be >1000

### ISSUE THREAD

**Issue by chrisns** [kubewarden/user-group-psp-policy#4]
Given this is a PSP replacement, I'm not sure why this additional validation needs to exist?

https://github.com/kubewarden/user-group-psp-policy/blob/e0bcc1f918f26d1790be3cd72993c4f6061ff9fa/src/settings.rs#L33-L42

**Comment by viccuad** [comment]
I am not the original author of the policy, but some of those are conventions that several Linux distributions follow; openSUSE, Debian and RHEL all reserve userids < 1000. And I know that the user `nobody` is `65534` in Fedora and Debian, at least.

For a list of conventions, the best that I have been able to find is the rules in [Debian Policy](https://www.debian.org/doc/debian-policy/ch-opersys.html#uid-and-gid-classes).

**Comment by chrisns** [comment]
I accept its a convention, but I don't see why that convention has crept into a validation in the policy, ultimately they're arbitrary numbers.
I should at least be able to bypass this check IMHO

**Comment by chrisns** [comment]
closed by #5
